### PR TITLE
PHP 8 support

### LINKED ISSUE #10: PHP 8.0.0 error due to incompatable dependency version
On PHP 8.0.0 an error is thrown. this is due to match becoming a reserved name this has been fixed bu the dependency author willdurand/negotiation. this composer JSON needs to reflect this to bump the version to ^3.0

|    Q        |   A
|------------ | ------
| Version(s)  1.2.0

#### Summary
In PHP 8.0.0 throws an unexpected error message

#### Current behavior
An unexpected error occurred; stack trace:

ParseError raised in file /home/cms/vendor/willdurand/negotiation/src/Negotiation/Negotiator.php line 41:
Message: syntax error, unexpected token "match"
Stack Trace:
```
#0 /home/cms/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/cms/vendo...')
#1 /home/cms/vendor/mezzio/mezzio-problem-details/src/ProblemDetailsMiddleware.php(102):
Composer\Autoload\ClassLoader->loadClass('Negotiation\\Neg...')
#2 /home/cms/vendor/mezzio/mezzio-problem-details/src/ProblemDetailsMiddleware.php(54):
Mezzio\ProblemDetails\ProblemDetailsMiddleware->canActAsErrorHandler(Object(Laminas\Diactoros\ServerRequest))
#3 /home/cms/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47):
Mezzio\ProblemDetails\ProblemDetailsMiddleware->process(Object(Laminas\Diactoros\ServerRequest),
Object(Laminas\Stratigility\Next))
#4 /home/cms/vendor/laminas/laminas-stratigility/src/Next.php(61):
Mezzio\Middleware\LazyLoadingMiddleware->process(Object(Laminas\Diactoros\ServerRequest),
Object(Laminas\Stratigility\Next))
#5 /home/cms/vendor/laminas/laminas-stratigility/src/Middleware/ErrorHandler.php(144):
Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#6 /home/cms/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47):
Laminas\Stratigility\Middleware\ErrorHandler->process(Object(Laminas\Diactoros\ServerRequest),
Object(Laminas\Stratigility\Next))
#7 /home/cms/vendor/laminas/laminas-stratigility/src/Next.php(61):
Mezzio\Middleware\LazyLoadingMiddleware->process(Object(Laminas\Diactoros\ServerRequest),
Object(Laminas\Stratigility\Next))
#8 /home/cms/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84):
Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#9 /home/cms/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(73):
Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest),
Object(Laminas\Stratigility\EmptyPipelineHandler))
#10 /home/cms/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96):
Laminas\Stratigility\MiddlewarePipe->handle(Object(Laminas\Diactoros\ServerRequest))
#11 /home/cms/vendor/mezzio/mezzio/src/Application.php(82): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#12 /home/cms/public/index.php(28): Mezzio\Application->run()
#13 /home/cms/public/index.php(29): {closure}()
#14 {main}
```
#### How to reproduce

run on PHP 8.0.0

#### Expected behavior
no error message

### PR DESCRIPTION
**Pull request by acelaya**
This is a continuation of #8 

It has the same changes plus these:

* Updated `willdurand/negotiation` to v3.
* Used `8.0` instead of `nightly` in travis file.
* Explicitly imported `Zend` classes aliased with the `Legacy` prefix.
* Removed `--ignore-platform-reqs` when installing dependencies in travis, as now all dependencies support PHP 8.
* Fixed coding styles.
* Fixed tests.

### CODE REVIEW

**Comment by acelaya** [comment]
I'm not sure why, but every single test is failing with this error `TypeError: Return value of PHPUnit\Framework\Constraint\Callback::matches() must be of the type bool, string returned`.

I reproduced it locally, but I'm running things through docker and I thought there was something wrong with my env. I see now it's not the case. I'll investigate what's going on.

File: src/ProblemDetailsResponseFactory.php [hunk 1]
```diff
@@ -330,15 +334,15 @@ private function cleanKeysForXml(array $input): array
     {
         $return = [];
         foreach ($input as $key => $value) {
-            $key = str_replace("\n", '_', $key);
+            $key                   = str_replace("\n", '_', (string) $key);
```
Comment (acelaya) [inline src/ProblemDetailsResponseFactory.php:337]: In PHP 8, a TypeError is thrown if the third param for `str_replace` is not a string or null.

One of the tests was failing because the keys were ints, and this was the attempt to fix it. It works, but the implicit casting could hide other problems, so I'm open for suggestions.

File: test/ProblemDetailsAssertionsTrait.php [hunk 2]
```diff
@@ -84,39 +83,41 @@ public function prepareResponsePayloadAssertions(
...
+            ->expects($this->any())
+            ->method('write')
+            ->with($this->callback(function ($body) use ($assertion) {
+                Assert::assertIsString($body);
                 $data = json_decode($body, true);
                 $assertion($data);
-                return $body;
-            }))
-            ->shouldBeCalled();
+                return true;
```
Comment (acelaya) [inline test/ProblemDetailsAssertionsTrait.php:97]: I have changed the return type of callbacks in a few places.

PHPUnit actually expects them to return a boolean, making the test fail if the value is `false`.

In previous versions there was an implicit casting, so returning any truthy value was considered as true. However, PHPUnit now has declared the return type as `bool`, making the tests fail because they were returning something else.

Since all of them are doing assertios before the return, I have changed the returns to simply `return true`.

File: phpunit.xml.dist [hunk 3]
```diff
@@ -1,17 +1,13 @@
...
-            <directory>./test</directory>
-        </testsuite>
-    </testsuites>
-
-    <filter>
-        <whitelist processUncoveredFilesFromWhitelist="true">
-            <directory suffix=".php">./src</directory>
-        </whitelist>
-    </filter>
+<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.3/phpunit.xsd" bootstrap="vendor/autoload.php" colors="true">
```
Comment (Ocramius) [inline phpunit.xml.dist]: This should be `xsi:noNamespaceSchemaLocation="vendor/phpunit/phpunit/phpunit.xsd"`, not a reference to a web URI

File: src/Exception/ProblemDetailsExceptionInterface.php [hunk 4]
```diff
@@ -18,21 +18,23 @@
...
     /**
      * Serialize the exception to an array of problem details.
      *
      * Likely useful for the JsonSerializable implementation, but also
      * for cases where the XML variant is desired.
      */
-    public function toArray() : array;
+    public function toArray(): array;
+
+    public function jsonSerialize();
```
Comment (Ocramius) [inline src/Exception/ProblemDetailsExceptionInterface.php]: This shouldn't be added: it's inherited from `JsonSerializable`

File: src/ProblemDetailsResponseFactory.php [hunk 5]
```diff
@@ -79,36 +82,36 @@ class ProblemDetailsResponseFactory
...
+        StatusCode::STATUS_IM_A_TEAPOT                     => 'I\'m a teapot',
+        StatusCode::STATUS_MISDIRECTED_REQUEST             => 'Misdirected Request',
+        StatusCode::STATUS_UNPROCESSABLE_ENTITY            => 'Unprocessable Entity',
+        StatusCode::STATUS_LOCKED                          => 'Locked',
+        StatusCode::STATUS_FAILED_DEPENDENCY               => 'Failed Dependency',
+        StatusCode::STATUS_UPGRADE_REQUIRED                => 'Upgrade Required',
+        StatusCode::STATUS_PRECONDITION_REQUIRED           => 'Precondition Required',
+        StatusCode::STATUS_TOO_MANY_REQUESTS               => 'Too Many Requests',
+        StatusCode::STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE => 'Request Header Fields Too Large',
+        444                                                => 'Connection Closed Without Response',
```
Comment (Ocramius) [inline src/ProblemDetailsResponseFactory.php:112]: Do these have static declarations now, perchance?

File: src/ProblemDetailsResponseFactory.php [hunk 6]
```diff
@@ -79,36 +82,36 @@ class ProblemDetailsResponseFactory
...
+        StatusCode::STATUS_UNAVAILABLE_FOR_LEGAL_REASONS   => 'Unavailable For Legal Reasons',
+        499                                                => 'Client Closed Request',
```
Comment (Ocramius) [inline src/ProblemDetailsResponseFactory.php:114]: Do these have static declarations now, perchance?

File: src/ProblemDetailsResponseFactory.php (hunk 1 above)
Comment (Ocramius) [reply src/ProblemDetailsResponseFactory.php:337]: Cast seems correct 👍

**Review by Ocramius — CHANGES_REQUESTED** [review]

File: src/ProblemDetailsResponseFactory.php (hunk 5 above)
Comment (acelaya) [reply src/ProblemDetailsResponseFactory.php:112]: They don't seem to be defined in the `StatusCodeInterface`.

File: src/Exception/ProblemDetailsExceptionInterface.php (hunk 4 above)
Comment (acelaya) [reply src/Exception/ProblemDetailsExceptionInterface.php]: It seems that it was added because PHPUnit's `createMock` does not detect the jsonSerializable otherwise, generating an object that doesn't implement it and throws an error at runtime.

I have fixed it by creating exception mocks with `new class extends Exception implements ProblemDetailsExceptionInterface {...}` instead.

**Comment by acelaya** [comment]
@Ocramius I have applied all requested changes. Feel free to review again.

File: test/ProblemDetailsMiddlewareFactoryTest.php [hunk 7]
```diff
@@ -13,39 +13,50 @@
...
+use PHPUnit\Framework\MockObject\MockObject;
 use PHPUnit\Framework\TestCase;
 use Psr\Container\ContainerInterface;
+use ReflectionObject;
 use RuntimeException;
 
 class ProblemDetailsMiddlewareFactoryTest extends TestCase
 {
-    protected function setUp() : void
+    /** @var ContainerInterface|MockObject */
```
Comment (Ocramius) [inline test/ProblemDetailsMiddlewareFactoryTest.php:24]: Not important for now, but in future, use `&` instead of  `|` in mock types, since a mock implements both interfaces at the same time.

This will pop up in static analysis :-)

**Review by Ocramius — APPROVED** [review]
🚢

**Comment by Ocramius** [comment]
Thanks @acelaya!

**Comment by acelaya** [comment]
Thanks! 🙂
